### ISSUE TITLE
Docs yang lebih lengkap?

### ISSUE THREAD

**Issue by mzaini30** [tomrichard/pusakaframework#1]
Di mana aku bisa mendapatkan docs yang lebih lengkap? Di webnya cuma ada getting started. Terutama, aku mau tau cara koneksi ke SQLite. Thanks

**Comment by tomrichard** [comment]
Untuk saat ini cuma masih support di mysql untuk update akan segera menyusul. Terimakasih atas supportnya. #1 sudah fixing di bawah.

**Comment by tomrichard** [comment]
@mzaini30 

Terimakasih atas atas partisipasi isuenya.
 
Untuk update driver sqlite telah selesai.
Documentasi nya ada di halaman berikut :

https://xdevpusaka.com/docs/2.0/query-builder

jika menggunakan rest api contohnya ada disini :

https://xdevpusaka.com/docs/2.0/rest-api#getstarted

atau jika mau menggunakan controller web app disini :

`<?php 
use Pusaka\Database\Manager;
use Pusaka\Hmvc\Controller;
use Pusaka\Http\Request;

use Pusaka\Database\Exceptions\DatabaseException;
use Pusaka\Database\Exceptions\SqlException;

class HelloCS extends Controller {

    function index() {

    	$row = [];

    	try {

	        $query = Manager::on('sqlite')->builder();

	        $query
	        	->select('col1', 'col2')
	        	->table('user');

	        // $sql = $query->getQuery(); // untuk debug sql

	        $row = $query->get();

	    }catch(DatabaseException $e) {
	    
	    	var_dump($e->getMessage());
	    
	    }catch(SqlException $e) {

	    	var_dump($e->getMessage());
	    
	    }

	    $this->load->view(compact('row'));

    }

}`

Utuk codenya dapat di pull atau clone di master.

**Comment by mzaini30** [comment]
@tomrichard Terima kasih banyak
